const CONTRACTIONS = {
  "don't":   { expanded: "do not",    translation: "no" },
  "doesn't": { expanded: "does not",  translation: "no" },
  "didn't":  { expanded: "did not",   translation: "no" },
  "won't":   { expanded: "will not",  translation: "no" },
  "wouldn't":{ expanded: "would not", translation: "no haría" },
  "can't":   { expanded: "can not",   translation: "no puede" },
  "couldn't":{ expanded: "could not", translation: "no podría" },
  "shouldn't":{ expanded: "should not",translation: "no debería" },
  "isn't":   { expanded: "is not",    translation: "no es/está" },
  "aren't":  { expanded: "are not",   translation: "no son/están" },
  "wasn't":  { expanded: "was not",   translation: "no era/estaba" },
  "weren't": { expanded: "were not",  translation: "no eran/estaban" },
  "haven't": { expanded: "have not",  translation: "no he/han" },
  "hasn't":  { expanded: "has not",   translation: "no ha" },
  "hadn't":  { expanded: "had not",   translation: "no había" },
  "i'm":     { expanded: "i am",      translation: "yo soy/estoy" },
  "i've":    { expanded: "i have",    translation: "yo he" },
  "i'll":    { expanded: "i will",    translation: "yo haré" },
  "i'd":     { expanded: "i would",   translation: "yo haría" },
  "you're":  { expanded: "you are",   translation: "tú eres/estás" },
  "you've":  { expanded: "you have",  translation: "tú has" },
  "you'll":  { expanded: "you will",  translation: "tú harás" },
  "he's":    { expanded: "he is",     translation: "él es/está" },
  "she's":   { expanded: "she is",    translation: "ella es/está" },
  "it's":    { expanded: "it is",     translation: "ello es/está" },
  "we're":   { expanded: "we are",    translation: "nosotros somos/estamos" },
  "they're": { expanded: "they are",  translation: "ellos son/están" },
  "there's": { expanded: "there is",  translation: "hay" },
  "that's":  { expanded: "that is",   translation: "eso es" },
  "what's":  { expanded: "what is",   translation: "qué es" },
  "let's":   { expanded: "let us",    translation: "vamos a" }
};

export { CONTRACTIONS };